project:
  type: website
  output-dir: docs

website:
  title: "R442-Survival_Quiz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exwecise1.qmd
        text: exercise1
      - href: answer.qmd
        text: quiz_answer

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

